# Generated by Django 5.0.1 on 2024-02-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('order_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('order', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to='login_app.credentialstable')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
    ]
