# Generated by Django 5.0.1 on 2024-02-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='username',
            new_name='user',
        ),
    ]
