# Generated by Django 5.0.1 on 2024-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTable',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('shipping_address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ShippingTable',
            },
        ),
    ]
