# Generated by Django 5.0.1 on 2024-02-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTable',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('shipping_address', models.CharField(max_length=300)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_to', to='login_app.credentialstable')),
            ],
            options={
                'db_table': 'ShippingTable',
            },
        ),
    ]
