# Generated by Django 5.0.1 on 2024-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTable',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.CharField(max_length=300)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ShippingTable',
            },
        ),
    ]
