# Generated by Django 5.0.1 on 2024-02-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingtable',
            old_name='user_id',
            new_name='user',
        ),
    ]
